dist: trusty
language: java
jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2

env:
  global:
  - secure: R3C4eAdh8jRdKxDGRNyXE7u8oe5Y/R+4uIYu7d/5UovJKFrv54Y/AjqpVIRiSSAEOe2ccSkTha2TjtROt5Ys+v6eLaZdnYaY0a1hZG0St5Q9FK+JcRsrxRJSkK45cyx19XQ6fysqlskzOuAxyQKo7zjZbvZOnZji/LUmsN/erNc=
  - secure: J93srOX2tKrLfD00rYxCSvyJGYzNS0bvmi7gy7WSjKZ+WBCo2anUxvFZM7dcH8C5BwfowCTSgjzE76bQlxlXMO84q7LaFRxil4lD1jqYONzCTwg0OhUpNJPuJPXPmOFEgQZaQy4ZaVDAhV9bL4RK+MK+rm5/rMZxMz7Pg8yp9dU=

install: true

before_script:
  - cp .travis.maven.settings.xml ~/.m2/settings.xml

script:
  - 'echo "TRAVIS_PULL_REQUEST value: $TRAVIS_PULL_REQUEST"'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn clean deploy --update-snapshots; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then mvn clean install --update-snapshots; fi' #Uses !="false" because $TRAVIS_PULL_REQUEST is the Pull Request number if such is the case.

