sudo: false
cache:
  directories:
  - $HOME/.m2/repository

language: java
jdk:
- oraclejdk8

env:
  global:
  - secure: gXwtInIsVABOYaWUKf/8nySvjH4nVtgoLW/WTRdFM8OwwV0Uh6BouGhKdOU6MuFyVfCeJa210mfdewnQeUyflTPjEY7VL4Xl2DGE3ZB/D2oUvjpMFOk5t9UuF9Mq/WsVKi2PJbw3DjkxSOv6LIK7B92ynVXIQ6XwpnWcyiPCNc4=
  - secure: jVopTl2j2mVwLhl/qQThSOgGfHGCQryEYiB2RELeNvekEQB/y3ypr9fH4dmJHEGHNzIQO/G+ZAHU95xok0KJBLL/di1LD0O3QsOsTZ7IblNOMXjsKTeLVXhvL7822JCAi4V9KfKpuDuXqSirQaeu+Bsie4wYCC2FHtirY3P2VM8=

before_install:
  - echo "<settings><servers><server><id>sonatype-oss-nexus-snapshots</id><username>\${env.SONATYPE_USER}</username><password>\${env.SONATYPE_PASS}</password></server></servers></settings>" > ~/.m2/deploy-settings.xml

install: true

script:
  - 'echo "TRAVIS_PULL_REQUEST value: $TRAVIS_PULL_REQUEST"'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn clean deploy --update-snapshots -PunitTests --settings ~/.m2/deploy-settings.xml; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then mvn clean install --update-snapshots -PunitTests; fi' #Uses !="false" because $TRAVIS_PULL_REQUEST is the Pull Request # if such is the case.

