sudo: false
cache:
  directories:
  - $HOME/.m2/repository

language: java
jdk:
- oraclejdk8

env:
  global:
  - secure: NTqf9WU84QecF0/WUgART8ACLW+0gejCPv5V4jgHQTxxRV4vUAxWjgTbC/XYuIvjbZkhMH91bKyyAMKwLUZVGTxnSQTbXOcyzaZVOX7shGcD+hELkpu3Rr1XlNJLIVWqTEckJN3McEDOhhxbfLU9oVwcK5UIM/nCYKjUfGsiWgA=
  - secure: SJYktPj7++ETN1wr3KeHg23h80DsMBtksoN5f56VcsimFNh2vVSaRq4J9Hw5h9uG8duehOGNUsGoesg2hL7xoM2SGrwXj7UnEsW3e0THFdMmWAOep+UUdAU2X6QhkHXUArbRTgmOsYBLdg6jhVx4skqV0QJHklO3JmIDw+aqlnA=

before_install:
  - echo "<settings><servers><server><id>sonatype-oss-nexus-snapshots</id><username>\${env.SONATYPE_USER}</username><password>\${env.SONATYPE_PASS}</password></server></servers></settings>" > ~/.m2/deploy-settings.xml

install: true

script:
  - 'echo "TRAVIS_PULL_REQUEST value: $TRAVIS_PULL_REQUEST"'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn clean deploy --update-snapshots -PunitTests --settings ~/.m2/deploy-settings.xml; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then mvn clean install --update-snapshots -PunitTests; fi' #Uses !="false" because $TRAVIS_PULL_REQUEST is the Pull Request # if such is the case.

